import React,{useState}from'react'
import{createRoot}from'react-dom/client'
import{Home,Users,ClipboardList,Star,Euro,PlaySquare,Menu,Bell,UserCircle,Cloud,FileDown,ChevronRight,Search,CalendarDays,Trophy,Target,Eye,BarChart3}from'lucide-react'
import{signInGoogle,createDriveFolder,uploadPdfToDrive}from'./services/google.js'
import{exportElementToPdf}from'./services/pdf.js'
import'./styles.css'
const tabs=[{"id": "profile", "label": "Perfil", "icon": "👤"}, {"id": "training", "label": "Treino", "icon": "📅"}, {"id": "squad", "label": "Plantel", "icon": "👥"}, {"id": "docs", "label": "Docs", "icon": "📂"}]
const sections={"profile": {"title": "Perfil do Jogador", "subtitle": "Informação pessoal e desportiva.", "cards": [{"title": "Seniores", "text": "Idade, peso, altura, posição, pé dominante."}, {"title": "Formação", "text": "Escalão, posição, encarregado e mensalidade."}, {"title": "Evolução", "text": "Avaliações e presenças."}, {"title": "Contactos", "text": "Dados autorizados."}], "items": ["Ficha do atleta", "Mensalidade nos escalões", "Histórico de treino", "PDF do perfil"]}, "training": {"title": "Treino", "subtitle": "Conteúdo partilhado pelo treinador.", "cards": [{"title": "Vídeos", "text": "Exercícios e animações."}, {"title": "PDFs", "text": "Esquemas e planos."}, {"title": "Plano semanal", "text": "O que treinar esta semana."}, {"title": "Notas", "text": "Notas do treinador."}], "items": ["Vídeo de exercício", "Esquema tático", "PDF do treino", "Plano semanal"]}, "squad": {"title": "Plantel", "subtitle": "Fichas dos colegas de equipa.", "cards": [{"title": "Jogadores", "text": "Nome, número e posição."}, {"title": "Seniores", "text": "Informação desportiva detalhada."}, {"title": "Formação", "text": "Perfil resumido."}, {"title": "Equipa", "text": "Plantel por escalão."}], "items": ["Ficha resumida", "Número e posição", "Aniversário/idade", "Dados autorizados"]}, "docs": {"title": "Documentos", "subtitle": "PDFs, calendário e pagamentos.", "cards": [{"title": "PDFs", "text": "Treinos e avaliações."}, {"title": "Mensalidade", "text": "Estado de pagamento."}, {"title": "Calendário", "text": "Treinos e jogos."}, {"title": "Drive", "text": "Documentos partilhados."}], "items": ["Plano em PDF", "Avaliação recebida", "Estado da mensalidade", "Calendário da equipa"]}}
function App(){const[tab,setTab]=useState(tabs[0].id);const[g,setG]=useState('offline');const[folder,setFolder]=useState(null)
async function connect(){try{setG('a ligar...'); await signInGoogle(); const f=await createDriveFolder('Cav Academy Player'); setFolder(f); setG('ligado')}catch(e){console.error(e);setG('erro');alert('Verifica CLIENT_ID e API_KEY')}}
async function pdf(name='Cav_Academy_Player.pdf'){try{const b=await exportElementToPdf('pdf-area',name); if(g==='ligado'){await uploadPdfToDrive(name,b,folder?.id); alert('PDF guardado no Drive')} else alert('PDF gerado. Liga ao Google para enviar ao Drive.')}catch(e){console.error(e);alert('Erro ao gerar PDF')}}
const cur=sections[tab]||sections[tabs[0].id]
return <div className="phone"><Header g={g} connect={connect}/><main id="pdf-area"><section className="hero"><h2>{cur.title}</h2><p>{cur.subtitle}</p><button onClick={()=>pdf(cur.title+'.pdf')}><FileDown size={18}/> Gerar PDF</button></section><div className="grid">{cur.cards.map((c,i)=><Card key={i} item={c}/>)}</div><div className="list">{cur.items.map((it,i)=><Row key={i} text={it}/>)}</div></main><nav>{tabs.map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}><span>{t.icon}</span><small>{t.label}</small></button>)}</nav></div>}
function Header({g,connect}){return <header><img src={`${import.meta.env.BASE_URL}logo-2you.png`}/><div><h1>CAV ACADEMY PLAYER</h1><p>JOGADOR</p></div><button className={g==='ligado'?'ok':''} onClick={connect}><Cloud size={18}/></button><Bell size={19}/><UserCircle size={22}/></header>}
function Card({item}){return <div className="card"><b>{item.title}</b><p>{item.text}</p></div>}
function Row({text}){return <div className="row"><div><b>{text}</b><p>Clique para consultar detalhes, PDF, Drive e histórico.</p></div><ChevronRight size={18}/></div>}
createRoot(document.getElementById('root')).render(<App/>)
